const constants = {
    ADD_HISTORY: "ADD_HISTORY",
    RESET_HISTORY: "RESET_HISTORY",
    CALCULATE_HISTORY: "CALCULATE_HISTORY",
    REWRITE_HISTORY: "REWRITE_HISTORY",
    ADD_CURRENT: "ADD_CURRENT",
    RESET_CURRENT: "RESET_CURRENT",
    ADD_PREVIOUS: "ADD_PREVIOUS",
    ADD_CURRENT_SIGN: "ADD_CURRENT_SIGN",
    EVALUATED: "EVALUATED"
}

export default constants